Curs Python/Saptamana 9 Django Project/proiect/aplicatie1/urls.py
from django.urls import path

from aplicatie1 import views

app_name = 'locations'

urlpatterns = [
    path('', views.LocationsView.as_view(), name='lista_locatii'),
    path('adaugare/', views.CreateLocationsView.as_view(), name='adaugare'),
    path('<int:pk>/update/', views.UpdateLocationsView.as_view(), name='modificare'),
    path('<int:pk>/delete/', views.delete_location, name='stergere'),
    path('<int:pk>/activate/', views.activate_location, name='activare'),

    path('start_timesheet/', views.new_timesheet, name='start_pontaj'),
    path('stop_timesheet/', views.stop_timesheet, name='oprire_pontaj'),
]

Curs Python/Saptamana 9 Django Project/proiect/proiect/urls.py
from django.contrib import admin
from django.contrib.auth.views import LoginView
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('locations/', include('aplicatie1.urls')),
    path('', include('django.contrib.auth.urls'), {'next_page': '/'}, name='login'),
    path('', LoginView.as_view(template_name='registration/login.html'), name='login'),
    path('userprofile/', include('userprofile.urls')),
]

Curs Python/Saptamana 9 Django Project/proiect/userprofile/urls.py
from django.urls import path

from userprofile import views

app_name = 'userprofile'

urlpatterns = [
    path('new_account/', views.CreateNewAccount.as_view(), name='utilizator_nou')
]

Curs Python/Saptamana 9 Django Project/proiect/aplicatie1/models.py
from django.db import models


class Location(models.Model):

    city = models.CharField(max_length=100)
    country = models.CharField(max_length=90)
    active = models.BooleanField(default=1)

    def __str__(self):
        return f"{self.country} -> {self.city}"


class Pontaj(models.Model):

    user = models.ForeignKey('auth.User', on_delete=models.CASCADE)
    start_date = models.DateTimeField()
    end_date = models.DateTimeField(null=True)

    def __str__(self):
        return f"{self.user} {self.start_date}"


class Logs(models.Model):
    action_choices = (('created', 'created'),
                      ('updated', 'updated'),
                      ('refresh', 'refresh'))

    created_at = models.DateTimeField(auto_now_add=True, blank=True)
    updated_at = models.DateTimeField(auto_now=True, blank=True)
    user = models.ForeignKey('auth.User', on_delete=models.CASCADE)
    action = models.CharField(max_length=10, choices=action_choices)
    url = models.CharField(max_length=100)

Curs Python/Saptamana 9 Django Project/proiect/userprofile/forms.py
from django import forms
from django.contrib.auth.models import User
from django.forms import TextInput


class NewAccountForm(forms.ModelForm):

    class Meta:
        model = User
        fields = ['first_name', 'last_name', 'email', 'username']

        widgets = {
            'first_name': TextInput(attrs={'placeholder': 'first name', 'class': 'form-control'}),
            'last_name': TextInput(attrs={'placeholder': 'last name', 'class': 'form-control'}),
            'email': TextInput(attrs={'placeholder': 'email', 'class': 'form-control'}),
            'username': TextInput(attrs={'placeholder': 'username', 'class': 'form-control'}),
        }

    def clean(self):
        field_data = self.cleaned_data
        email_value = field_data.get('email')
        if User.objects.filter(email=email_value).exists():
            msg = "Emailul deja exista! Te rugam sa adaugi un alt email"
            self._errors['email'] = self.error_class([msg])
        return field_data

Curs Python/Saptamana 9 Django Project/proiect/aplicatie1/views.py
import datetime

from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import HttpResponseRedirect
from django.shortcuts import render, redirect

# Create your views here.
from django.urls import reverse
from django.views.generic import ListView, CreateView, UpdateView

# ListView -> listarea datelor dintr-un model
# CreateView -> adaugarea datelor in db
# UpdateView -> modificarea datelor din db
from aplicatie1.models import Location, Pontaj


class LocationsView(LoginRequiredMixin, ListView):
    model = Location
    template_name = 'aplicatie1/locations_index.html'


class CreateLocationsView(LoginRequiredMixin, CreateView):
    model = Location
    fields = ['city', 'country']
    template_name = 'aplicatie1/locations_form.html'

    def get_success_url(self):
        return reverse('locations:lista_locatii')


class UpdateLocationsView(LoginRequiredMixin, UpdateView):
    model = Location
    fields = ['city', 'country']
    template_name = 'aplicatie1/locations_form.html'

    def get_success_url(self):
        return reverse('locations:lista_locatii')


@login_required
def delete_location(request, pk):
    """
    model.objects.get(coloana1=val, caloana2=val2) -> returneaza intotdeauna o singura inregistrae
                        -> daca nu exista nimic in baza de date sau exista mai multe inregistrari conform cautarilor,
                        apare eroare
                        -> Location.objects.get().city
    model.objects.filter(coloana1=val, caloana2=val2) -> returneaza intotdeauan mai multe inregistrari
                           -> daca nu exista nicio inregistrare sau exista mai multe inregistrari, nu apare eroare
    :param request:
    :param pk:
    :return:
    """
    Location.objects.filter(id=pk).update(active=0)
    return redirect('locations:lista_locatii')


@login_required
def activate_location(request, pk):
    Location.objects.filter(id=pk).update(active=1)
    return redirect('locations:lista_locatii')


@login_required
def new_timesheet(request):
    Pontaj.objects.create(user_id=request.user.id, start_date=datetime.datetime.now())
    return HttpResponseRedirect(request.META.get('HTTP_REFERER'))


@login_required
def stop_timesheet(request):
    Pontaj.objects.filter(user_id=request.user.id, end_date=None).update(end_date=datetime.datetime.now())
    return HttpResponseRedirect(request.META.get('HTTP_REFERER'))

Curs Python/Saptamana 9 Django Project/proiect/userprofile/views.py
import random
import string

from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.models import User
from django.core.mail import EmailMultiAlternatives
from django.shortcuts import render

# Create your views here.
from django.template.loader import render_to_string
from django.urls import reverse
from django.views.generic import CreateView

from userprofile.forms import NewAccountForm


class CreateNewAccount(LoginRequiredMixin, CreateView):
    model = User
    template_name = 'aplicatie1/locations_form.html'
    form_class = NewAccountForm

    def form_invalid(self, form):
        print(form.errors.as_json())
        return super().form_invalid(form)

    def get_success_url(self):
        psw = ''.join(random.SystemRandom().choice(string.ascii_uppercase + string.ascii_lowercase +
                                                   string.digits + '!$%?#@') for _ in range(8))
        if (user_instance := User.objects.filter(id=self.object.id)) and user_instance.exists():
            user_object = user_instance.first()
            user_object.set_password(psw)
            user_object.save()

            content = f"Datele de autentificare sunt: \n {user_object.username} \n {psw}"
            msg_html = render_to_string('registration/invite_user.html', {'content_email': content})
            email = EmailMultiAlternatives(subject='Date conectare aplicatie',
                                           body=content,
                                           from_email='contact@test.ro',
                                           to=[user_object.email])
            email.attach_alternative(msg_html, 'text/html')
            email.send()
        return reverse('locations:lista_locatii')

Curs Python/Saptamana 9 Django Project/proiect/templates/aplicatie1/locations_form.html
{% extends 'base.html' %}
{% block content %}
    <form method="post">
        {% csrf_token %}
        {% for field in form %}
            {{ field.label }} {{ field }} {{ field.errors }} <br>
        {% endfor %}
    <button type="submit" class="btn btn-danger">Salveaza</button>
    </form>
{% endblock %}

Curs Python/Saptamana 9 Django Project/proiect/templates/aplicatie1/locations_index.html
{% extends 'base.html' %}
{% block content %}
    <a class="btn btn-primary" href="{% url 'locations:adaugare' %}">Adaugare locatii</a>
    <table class="table">
        <thead>
        <tr>
            <th>Index</th>
            <th>City</th>
            <th>Country</th>
            <th>Active</th>
            <th>Actions</th>
        </tr>
        </thead>
        <tbody>
        {% for item in location_list %}
            <tr>
                <td>{{ forloop.counter }}</td>
                <td>{{ item.city }}</td>
                <td>{{ item.country }}</td>
                <td>
                    {% if item.active %}
                        Activ
                    {% else %}
                        Inactiv
                    {% endif %}
                </td>
                <td><a class="btn btn-success" href="{% url 'locations:modificare' item.id %}">Editare</a>
                    {% if item.active %}
                        <a class="btn btn-warning" href="{% url 'locations:stergere' item.id %}">Stergere</a>
                    {% else %}
                        <a class="btn btn-warning" href="{% url 'locations:activare' item.id %}">Activeaza</a>
                    {% endif %}
                </td>
            </tr>
        {% endfor %}
        </tbody>
    </table>
{% endblock %}

Curs Python/Saptamana 9 Django Project/proiect/templates/base.html
<html>
<head>
    {% block title %}
    {% endblock %}
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css">
</head>
<body>
<div class="container">
    <div class="row">
        <div class="col-md-12">
            <nav>
                <a class="btn" href="/admin">Admin</a>
                {% if request.user.is_authenticated %}
                    <span>Hi, {{ request.user.username|upper }}</span>
                    <a class="btn" href="{% url 'locations:lista_locatii' %}">Locatii</a>
                    <a class="btn btn-primary" href="{% url 'logout' %}">Logout</a>
                    {% if ready_to_work is False %}
                        <a href="{% url 'locations:oprire_pontaj' %}" class="btn btn-danger">Oprire pontaj</a>
                    {% else %}
                        <a href="{% url 'locations:start_pontaj' %}" class="btn btn-success">Pornire pontaj</a>
                    {% endif %}
                    <a class="btn btn-danger" href="{% url 'userprofile:utilizator_nou' %}">New account</a>
                {% endif %}
            </nav>
        </div>
    </div>
</div>
{% block content %}
{% endblock %}
</body>
<footer>
    <div class="container"><p class="copyright pull-right"> &copy; {% now 'Y' %}SIIT</p></div>
</footer>
</html>